# -*- coding: utf-8 -*-
"""data mining_movie sample_nia refianita(4112322004).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Co3OK-IkCh_D4OW54J1_H664ZVuwWfU
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

#Memuat data dari file CSV
df = pd.read_csv('movie_sample_dataset.csv')

#Menampilkan 5 baris pertama dari dataset
df.head()

import numpy as np

# mengganti "?" dengan Nan
df.replace("?", np.nan, inplace=True)

# memeriksa jumlah missing values di setiap kolom
print(df.isnull().sum())

# Menghapus baris yang memiliki nilai NaN di kolom 'gross' dan 'budget'
df_cleaned = df.dropna(subset=['gross', 'budget'])

print(df_cleaned)

# Mengganti huruf color
df['color'] = df['color'].replace('Color','color')  # Misalnya mengganti "Color" dengan "color"

print(df)

# Mengganti 'N/A' dengan NaN dan nilai negatif dengan 0
df = df.replace('N/A', np.nan)
df = df.applymap(lambda x: 0 if isinstance(x, (int, float)) and x < 0 else x)

print(df)

# Mengonversi menjadi tipe integer (jika memungkinkan) atau float
df['budget'] = df['budget'].astype('Int64')  # Tipe integer
df['gross'] = df['gross'].astype(float)  # Tipe float

print(df)

# Fungsi untuk normalisasi teks: ubah menjadi huruf kecil
def normalize_text(text):
    if isinstance(text, str):  # Periksa apakah teks adalah string
        text = text.lower().strip()
        return text
    return text

# Terapkan fungsi normalisasi ke seluruh DataFrame
df = df.applymap(normalize_text)

print(df)

#df.to_csv('movie_sample_dataset_cleaned_df.csv') # This line was commented out, preventing the file from being saved.
df.to_csv('movie_dataset_cleaned_df.csv') # Save the DataFrame to a CSV file named 'clean_df.csv'.

# Download file CSV ke komputer
files.download('movie_dataset_cleaned_df.csv') # Changed file name to match the saved file.